name: CI Test
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get repository code
        uses: actions/checkout@v3
      - name: install g++
        uses: egor-tensin/setup-gcc@v1
        with: 
          version: latest
          platform: x64
      - name: print dir
        run: ls -a
      - name: compile code
        run: g++ any.cpp -o any
      - name: launch
        run: ./any.out
      
