name: CI Test
on: [workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v3
      - uses: egor-tensin/setup-gcc@v1
        with: 
          version: latest
          platform: x64
      - run: ls -a
      - run: g++ any.cpp
      
